Real_Estate/Controllers/EntityController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Metadata;
using Microsoft.AspNetCore.Mvc;
using Real_Estate.Models;
using Real_Estate.Models.Enums;
using Real_Estate.ViewModels;
using Real_Estate.ViewModels.Data;
using Real_Estate.ViewModels.Repository;

namespace Real_Estate.Controllers
{
    public class EntityController : Controller
    {
        private readonly AppDbContext context;
        private readonly AgencijaRepository agencijaRepository;
        private readonly KorisnikRepository korisnikRepository;

        public EntityController(AppDbContext _context, AgencijaRepository _agencijaRepository, KorisnikRepository _korisnikRepository)
        {
            context = _context;
            agencijaRepository = _agencijaRepository;
            korisnikRepository = _korisnikRepository;
        }
        public IActionResult Index()
        {         
            return View();
        }


        [HttpGet]
        public IActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public IActionResult LogIn(Korisnik korisnik)
        {
            Korisnik korisnik1 = korisnikRepository.FindByEmail(korisnik.Email);
            if (korisnik1!=null && korisnik1.Password==korisnik.Password )
            {
                HttpContext.Session.SetInt32("idkorisnika", korisnik1.IdKorisnika);
                if (korisnik1.IdTipKorisnika == TipKorisnika.Owner)
                {
                    return RedirectToAction("PocetnaProdavac", "Nekretnine");
                }
                else if(korisnik1.IdTipKorisnika == TipKorisnika.Customer)
                {
                    return RedirectToAction("PocetnaProdavac", "Nekretnine");//korisnik pocetna
                }
                else if (korisnik1.IdTipKorisnika == TipKorisnika.Admin)
                {
                    return RedirectToAction("PocetnaAdmin", "Admin");//admin sranica
                }
                else
                {
                    return View("LogIn");
                }
            }
            else
            {
                ViewBag.Poruka = "Email ili Password nisu validni";
                return View("LogIn");
            }   
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return View("LogIn");
        }

        [HttpGet]
        public IActionResult Registracija()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registracija(Korisnik korisnik)
        {
            if (korisnikRepository.FindByUserName(korisnik.Username) != null)
            {
                ViewBag.Poruka = "Korisnik sa datim UserName-om vec postoji";
                return View("Registracija");
            }

            string poruka=KorisnikViewModel.ProveraKorisnika(korisnik);
           
            if (poruka == "Ok")
            {
                if(korisnik.IdTipKorisnika==TipKorisnika.Owner && agencijaRepository.FindById(korisnik.IdAgencije)==null)
                {
                    ViewBag.Poruka = "Agencija sa datim Id-em ne postoji";
                    return View("Registracija");
                }

                korisnikRepository.AddUser(korisnik);
                return View("LogIn");
            }
            else
            {
                ViewBag.Poruka = poruka;
            }
            return View("Registracija");
        }

        [HttpGet]
        public IActionResult Profil()
        {
            int id = (int)HttpContext.Session.GetInt32("idkorisnika");
            Korisnik korisnik = korisnikRepository.FindById(id);
            return View(korisnik);
        }

        [HttpGet]
        public IActionResult UrediProfil()
        {
            int id = (int)HttpContext.Session.GetInt32("idkorisnika");
            Korisnik korisnik = korisnikRepository.FindById(id);
            return View(korisnik);
        }

        [HttpPost]
        public IActionResult UrediProfil(Korisnik korisnik)
        {
            int id = (int)HttpContext.Session.GetInt32("idkorisnika");
            string poruka = KorisnikViewModel.ProveraKorisnika(korisnik);

            if (poruka == "Ok")
            {
                if (korisnik.IdTipKorisnika == TipKorisnika.Owner && agencijaRepository.FindById(korisnik.IdAgencije) == null)
                {
                    ViewBag.Poruka = "Agencija sa datim Id-em ne postoji";
                    return View("Profil");
                }

                korisnikRepository.UpdateUser(korisnik);
                return View("Profil",korisnik);
            }
            else
            {
                ViewBag.Poruka = poruka;
            }

            return View("Profil",korisnikRepository.FindById(id));
        }

    }
}

Real_Estate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Real_Estate</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Real_Estate.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        
        <nav class="navbar navbar-expand-lg navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow pb-0">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Real_Estate</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 ms-auto">
                        @{
                            if (Context.Session.GetInt32("idkorisnika") != null )
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Nekretnine" asp-action="PocetnaProdavac">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Entity" asp-action="Profil">Profil</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Entity" asp-action="Logout">Logout</a>
                                </li>
                            }
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid p-0">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Real_Estate - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>