Real_Estate/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Real_Estate.Models;
using Real_Estate.ViewModels;
using Real_Estate.ViewModels.Data;
using Real_Estate.ViewModels.Repository;

namespace Real_Estate.Controllers
{
    public class AdminController : Controller
    {
        private readonly KorisnikRepository korisnikRepository;
        private readonly GradoviRepository gradoviRepository;
        private readonly MikrolokacijaRepository mikrolokacijaRepository;
        private readonly UlicaRepository ulicaRepository;
        private readonly AgencijaRepository agencijaRepository;
        private readonly NekretnineRepository nekretnineRepository;

        public AdminController(KorisnikRepository _korisnikRepository, GradoviRepository _gradoviRepository, MikrolokacijaRepository _mikrolokacijaRepository,
            UlicaRepository _ulicaRepository, AgencijaRepository _agencijaRepository, NekretnineRepository _nekretnineRepository)
        {
            korisnikRepository = _korisnikRepository;
            gradoviRepository = _gradoviRepository;
            mikrolokacijaRepository = _mikrolokacijaRepository;
            ulicaRepository = _ulicaRepository;
            agencijaRepository = _agencijaRepository;
            nekretnineRepository = _nekretnineRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult PocetnaAdmin()
        {          
            ViewData["Gradovi"] = gradoviRepository.GetAllGradovi();
            return View();
        }
        [HttpPost]
        public IActionResult PocetnaAdmin(int? IdGrada, string tipKorisnika)
        {
            ViewData["Gradovi"] = gradoviRepository.GetAllGradovi();
            if(IdGrada != null && tipKorisnika != null)
            {
                List<Korisnik> korisnici = korisnikRepository.FindByIdTipKorisnikaIdGrada(IdGrada, tipKorisnika);
                return View(korisnici);
            }
            return View();
        }
        [HttpGet]
        public IActionResult Agencije()
        {
            ViewData["Gradovi"] = gradoviRepository.GetAllGradovi();
            return View();
        }
        [HttpPost]
        public IActionResult Agencije(int idGrada)
        {
            ViewData["Gradovi"] = gradoviRepository.GetAllGradovi();
            List<Agencija> agencije = agencijaRepository.GetAllAgencija(idGrada);
            return View(agencije);
        }      
        [HttpGet]
        public IActionResult DodajAgenciju()
        {
            ViewBag.Gradovi = gradoviRepository.GetAllGradovi();
            return View();
        }
        [HttpPost]
        public IActionResult DodajAgenciju(Agencija agencija)
        {            
            string poruka = AgencijaViewModel.ProveraAgencije(agencija);
            if (poruka=="Ok")
            {
                agencijaRepository.AddAgenciju(agencija);
            }
            ViewBag.Gradovi = gradoviRepository.GetAllGradovi();
            return RedirectToAction("Agencije");
        }
        [HttpGet]
        public IActionResult UrediAgenciju(int IdAgencije)//stranica za promenu podataka(edit)
        {
            ViewBag.Gradovi = gradoviRepository.GetAllGradovi();
            Agencija agencija = agencijaRepository.FindById(IdAgencije);
            return View(agencija);
        }
        [HttpPost]
        public IActionResult UrediAgenciju(Agencija agencija)//stranica za promenu podataka(edit) o agenciji
        {
            
            string poruka = AgencijaViewModel.ProveraAgencije(agencija);
            if (poruka == "Ok")
            {
                agencijaRepository.UpdateAgencija(agencija);
                ViewBag.Gradovi = gradoviRepository.GetAllGradovi();
                return View("Agencije");
            }
            else
            {
                ViewBag.Poruka = poruka;
            }
            ViewBag.Gradovi = gradoviRepository.GetAllGradovi();
            return View("Agencije");
        }
        [HttpPost]
        public IActionResult BrisiAgenciju(int IdAgencije)
        {
            agencijaRepository.DeleteAgenciju(IdAgencije);
            return RedirectToAction("Agencije");
        }

        [HttpGet]
        public IActionResult Mikrolokacije()
        {
            ViewData["Gradovi"] = gradoviRepository.GetAllGradovi();           
            return View();
        }
        [HttpPost]
        public IActionResult Mikrolokacije(int idopstine)
        {
            ViewData["Gradovi"] = gradoviRepository.GetAllGradovi();           
            List<Mikrolokacija> mikrolokacije = mikrolokacijaRepository.GetAllMikrolokacija(idopstine);
            return View(mikrolokacije);
        }
        [HttpPost]
        public IActionResult BrisiMikrolokaciju(int IdMikrolokacije)
        {
            mikrolokacijaRepository.DeleteMikrolokacija(IdMikrolokacije);
            return RedirectToAction("Mikrolokacije");
        }
        [HttpGet]
        public IActionResult DodajMikrolokacije()
        {
            ViewBag.Gradovi = gradoviRepository.GetAllGradovi();
            return View();
        }
        [HttpPost]
        public IActionResult DodajMikrolokacije(Mikrolokacija mikrolokacija)
        {
            if(mikrolokacija.NazivMikrolokacije !=null && mikrolokacija.IdOpstine != null)
            {
                mikrolokacijaRepository.AddMikrolokacija(mikrolokacija);
            }
            ViewBag.Gradovi = gradoviRepository.GetAllGradovi();
            return RedirectToAction("Mikrolokacije");
        }
        [HttpGet]
        public IActionResult Ulice()
        {
            ViewData["Gradovi"] = gradoviRepository.GetAllGradovi();
            return View();
        }
        [HttpPost]
        public IActionResult Ulice(int idmikrolokacije)
        {
            ViewData["Gradovi"] = gradoviRepository.GetAllGradovi();
            List<Ulica> ulice = ulicaRepository.GetAllUlica(idmikrolokacije);
            return View(ulice);
        }
        [HttpPost]
        public IActionResult BrisiUlicu(int IdUlice)
        {
            ulicaRepository.DeleteUlica(IdUlice);
            return RedirectToAction("Ulice");
        }
        [HttpGet]
        public IActionResult DodajUlicu()
        {
            ViewBag.Gradovi = gradoviRepository.GetAllGradovi();
            return View();
        }
        [HttpPost]
        public IActionResult DodajUlicu(Ulica ulica)
        {
            if (ulica.NazivUlice != null && ulica.IdMikrolokacije != null)
            {
                ulicaRepository.AddUlica(ulica);
            }
            ViewBag.Gradovi = gradoviRepository.GetAllGradovi();
            return RedirectToAction("Ulice");
        }
        [HttpGet]
        public IActionResult ProdateNekretnine()// grad i opstina, tip nekretnine
        {
            ViewBag.Gradovi = gradoviRepository.GetAllGradovi();
            return View();
        }

        [HttpPost]
        public IActionResult ProdateNekretnine(int IdOpstine, string tipStanja , string tipNekretnine)
        {
            //nije dovrseno FindNekretnineByIdOpstine u NekretnineRepository

            if (IdOpstine !=null && tipStanja!=null && tipNekretnine != null)
            {
                List<Nekretnine> nekretnine=nekretnineRepository.FindNekretnineByIdOpstine(IdOpstine, tipStanja, tipNekretnine);
                return View(nekretnine);
            }
            return View();
        }
    }
}

Real_Estate/Controllers/NekretnineController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Real_Estate.Models;
using Real_Estate.ViewModels.Data;
using Real_Estate.ViewModels.Repository;

namespace Real_Estate.Controllers
{
    public class NekretnineController : Controller
    {
        private readonly NekretnineRepository nekretnineRepository;
        private readonly OpstinaRepository opstinaRepository;
        private readonly GradoviRepository gradoviRepository;
        private readonly MikrolokacijaRepository mikrolokacijaRepository;
        private readonly UlicaRepository ulicaRepository;

        public NekretnineController(NekretnineRepository _nekretnineRepository, OpstinaRepository _opstinaRepository, 
            GradoviRepository _gradoviRepository, MikrolokacijaRepository _mikrolokacijaRepository, UlicaRepository _ulicaRepository)
        {
            nekretnineRepository = _nekretnineRepository;
            opstinaRepository = _opstinaRepository;
            gradoviRepository = _gradoviRepository;
            mikrolokacijaRepository = _mikrolokacijaRepository;
            ulicaRepository = _ulicaRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult PocetnaProdavac()
        {           
            int id= (int)HttpContext.Session.GetInt32("idkorisnika");
            List<Nekretnine> nekretnine= nekretnineRepository.FindNekretnineByProdavac(id);
            return View("PocetnaProdavac",nekretnine);
        }

        [HttpGet]
        public IActionResult NovaNekretnina()
        {
            ViewBag.Gradovi= gradoviRepository.GetAllGradovi();
            return View();
        }
        public JsonResult GetOpstinaByGrad(int cityId)
        {
            List<Opstina> opstine = opstinaRepository.GetAllOpstina(cityId);
            return Json(opstine);
        }
        public JsonResult GetMikrolokacijaByOpstina(int opstinaId)
        {
            List<Mikrolokacija> mikrolokacije = mikrolokacijaRepository.GetAllMikrolokacija(opstinaId);
            return Json(mikrolokacije);
        }
        public JsonResult GetUlicaByMikrolokacija(int mikrolokacijaId)
        {
            List<Ulica> ulice = ulicaRepository.GetAllUlica(mikrolokacijaId);
            return Json(ulice);
        }
        

        [HttpPost]
        public IActionResult NovaNekretnina(Nekretnine nekretnine)
        {
            int id = (int)HttpContext.Session.GetInt32("idkorisnika");
            return View();
        }
    }
}

Real_Estate/Views/Admin/DodajAgenciju.cshtml
@model Real_Estate.Models.Agencija
@{

}
@*@section scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#CityId").change(function () {
                //console.log("usao u funkciju CityId");
                var selectedCityId = $(this).val();
                if (selectedCityId !== '') {
                    $.ajax({
                        url: '@Url.Action("GetOpstinaByGrad", "Nekretnine")',
                        type: 'GET',
                        data: { cityId: selectedCityId },
                        success: function (data) {
                            var opstineDropdown = $("#IdOpstine");
                            opstineDropdown.empty();
                            //console.log(data);
                            $.each(data, function (index, item) {
                                opstineDropdown.append($('<option/>', {
                                    value: item.idOpstine,
                                    text: item.nazivOpstine
                                }));
                            });
                        }
                    });
                }
                else {
                    $("#IdOpstine").empty();
                }
            });
            $("#IdOpstine").change(function () {
                // console.log("usao u funkciju OpstinaId");
                var selectedOpstinaId = $(this).val();
                // console.log(selectedOpstinaId);
                if (selectedOpstinaId !== '') {
                    $.ajax({
                        url: '@Url.Action("GetMikrolokacijaByOpstina", "Nekretnine")',
                        type: 'GET',
                        data: { opstinaId: selectedOpstinaId },
                        success: function (data) {
                            var mikrolokacijeDropdown = $("#IdMikrolokacije");
                            mikrolokacijeDropdown.empty();
                            //console.log(data);
                            $.each(data, function (index, item) {
                                mikrolokacijeDropdown.append($('<option/>', {
                                    value: item.idMikrolokacije,
                                    text: item.nazivMikrolokacije
                                }));
                            });
                        }
                    });
                }
                else {
                    $("#IdMikrolokacije").empty();
                }
            });

        });
    </script>
    }*@
<style>
    .nav-pills li a:hover {
        background-color: blue;
    }
</style>
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="bg-dark col-auto col-md-2 min-vh-100 ">
            <div class="bg-dark p-2">
                <a class="d-flex text-decoration-none mt-5 align-items-center text-white">
                    <span class="fs-4 d-none d-sm-inline">SideMenu</span>
                </a>
                <ul class="nav nav-pills flex-column mt-4">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/Admin/PocetnaAdmin">
                            Pocetna
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/Admin/ProdateNekretnine">
                            Prodate nekretnine
                        </a>
                    </li>
                    <li class="nav-item py-2 py-sm-0">
                        <a class="nav-link text-white" href="/Admin/Agencije">
                            Agencije
                        </a>
                    </li>
                    <li class="nav-item py-2 py-sm-0">
                        <a class="nav-link text-white" href="/Admin/Mikrolokacije">
                            Mikrolokacije
                        </a>
                    </li>
                    <li class="nav-item py-2 py-sm-0">
                        <a class="nav-link text-white" href="/Admin/Ulice">
                            Ulice
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="container">
            <div class="col-md-9 main-content">
                <form method="post" asp-action="DodajAgenciju" asp-controller="Admin" enctype="multipart/form-data">
                    <div class="form-group mb-2">
                        @* <label class="control-label">Naziv Mikrolokacije</label>*@
                        <div>
                            <input class="form-control" type="text" asp-for="Naziv" name="Naziv" placeholder="Naziv Agencije" />
                            <span asp-validation-for="Naziv" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group mb-2">
                        @* <label class="control-label">Naziv Mikrolokacije</label>*@
                        <div>
                            <input class="form-control" type="text" asp-for="PIB" name="PIB" placeholder="PIB" />
                            <span asp-validation-for="PIB" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group mb-2">
                        @* <label class="control-label">Naziv Mikrolokacije</label>*@
                        <div>
                            <input class="form-control" type="text" asp-for="Adresa" name="Adresa" placeholder="Adresa" />
                            <span asp-validation-for="Adresa" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group mb-2">
                        @* <label class="control-label">Naziv Mikrolokacije</label>*@
                        <div>
                            <input class="form-control" type="text" asp-for="Telefon" name="Telefon" placeholder="Telefon" />
                            <span asp-validation-for="Telefon" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group mb-2">
                        <label class="control-label">Grad</label>
                        <div>
                            <select class="form-select" id="IdGrada" name="IdGrada">
                                <option value="None" selected>Izaberi Grad</option>
                                @{
                                    foreach (var grad in ViewBag.Gradovi)
                                    {
                                        <option value="@grad.IdGrada">@grad.NazivGrada</option>
                                    }
                                }
                            </select>
                            
                        </div>
                    </div>                   
                    <div class="form-group text-center ">
                        <br />
                        <input type="submit" class="btn btn-primary btn-lg form-control" name="DodajAgenciju" value="Nova Agencija" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Real_Estate/Views/Admin/DodajMikrolokacije.cshtml
@model Real_Estate.Models.Mikrolokacija
@{

}
@section scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#CityId").change(function () {
                //console.log("usao u funkciju CityId");
                var selectedCityId = $(this).val();
                if (selectedCityId !== '') {
                    $.ajax({
                        url: '@Url.Action("GetOpstinaByGrad", "Nekretnine")',
                        type: 'GET',
                        data: { cityId: selectedCityId },
                        success: function (data) {
                            var opstineDropdown = $("#IdOpstine");
                            opstineDropdown.empty();
                            //console.log(data);
                            $.each(data, function (index, item) {
                                opstineDropdown.append($('<option/>', {
                                    value: item.idOpstine,
                                    text: item.nazivOpstine
                                }));
                            });
                        }
                    });
                }
                else {
                    $("#IdOpstine").empty();
                }
            }); 
        });
    </script>
    }


<style>
    .nav-pills li a:hover {
        background-color: blue;
    }
</style>
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="bg-dark col-auto col-md-2 min-vh-100 ">
            <div class="bg-dark p-2">
                <a class="d-flex text-decoration-none mt-5 align-items-center text-white">
                    <span class="fs-4 d-none d-sm-inline">SideMenu</span>
                </a>
                <ul class="nav nav-pills flex-column mt-4">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/Admin/PocetnaAdmin">
                            Pocetna
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/Admin/ProdateNekretnine">
                            Prodate nekretnine
                        </a>
                    </li>
                    <li class="nav-item py-2 py-sm-0">
                        <a class="nav-link text-white" href="/Admin/Agencije">
                            Agencije
                        </a>
                    </li>
                    <li class="nav-item py-2 py-sm-0">
                        <a class="nav-link text-white" href="/Admin/Mikrolokacije">
                            Mikrolokacije
                        </a>
                    </li>
                    <li class="nav-item py-2 py-sm-0">
                        <a class="nav-link text-white" href="/Admin/Ulice">
                            Ulice
                        </a>
                    </li>
                </ul>
            </div>
        </div>
       <div class="container">
            <div class="col-md-9 main-content">
                <form method="post" asp-action="DodajMikrolokacije" asp-controller="Admin" enctype="multipart/form-data">
                    <div class="form-group mb-2">
                        <label class="control-label">Naziv Mikrolokacije</label>
                        <div>
                            <input class="form-control" type="text" asp-for="NazivMikrolokacije" name="NazivMikrolokacije"  />
                            <span asp-validation-for="NazivMikrolokacije" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group mb-2">
                       @* <label class="control-label">Grad</label>*@
                        <div>
                            <select class="form-select" id="CityId" name="CityId">
                                <option value="None" selected>Izaberi Grad</option>
                                @{
                                    foreach (var grad in ViewBag.Gradovi)
                                    {
                                        <option value="@grad.IdGrada">@grad.NazivGrada</option>
                                    }
                                }
                            </select>
                            @*<span asp-validation-for="IdTipGrejanja" class="text-danger"></span>*@
                        </div>
                    </div>
                    <div class="form-group mb-2">
                       @* <label class="control-label">Opstina</label>*@
                        <div>
                            <select class="form-select" id="IdOpstine" name="IdOpstine">
                                <option value="None" selected>Izaberi Opstinu</option>
                                <option></option>
                            </select>
                            @*<span asp-validation-for="IdTipGrejanja" class="text-danger"></span>*@
                        </div>
                    </div>
                    <div class="form-group text-center ">
                        <br />
                        <input type="submit" class="btn btn-primary btn-lg form-control" name="DodajMikrolokacije" value="Nova Mikrolokacija" />
                    </div>
                </form>
            </div>
       </div>
    </div>
</div>

Real_Estate/Views/Admin/DodajUlicu.cshtml
@model Real_Estate.Models.Ulica
@{

}
@section scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#CityId").change(function () {
                //console.log("usao u funkciju CityId");
                var selectedCityId = $(this).val();
                if (selectedCityId !== '') {
                    $.ajax({
                        url: '@Url.Action("GetOpstinaByGrad", "Nekretnine")',
                        type: 'GET',
                        data: { cityId: selectedCityId },
                        success: function (data) {
                            var opstineDropdown = $("#IdOpstine");
                            opstineDropdown.empty();
                            //console.log(data);
                            $.each(data, function (index, item) {
                                opstineDropdown.append($('<option/>', {
                                    value: item.idOpstine,
                                    text: item.nazivOpstine
                                }));
                            });
                        }
                    });
                }
                else {
                    $("#IdOpstine").empty();
                }
            });
            $("#IdOpstine").change(function () {
                // console.log("usao u funkciju OpstinaId");
                var selectedOpstinaId = $(this).val();
                // console.log(selectedOpstinaId);
                if (selectedOpstinaId !== '') {
                    $.ajax({
                        url: '@Url.Action("GetMikrolokacijaByOpstina", "Nekretnine")',
                        type: 'GET',
                        data: { opstinaId: selectedOpstinaId },
                        success: function (data) {
                            var mikrolokacijeDropdown = $("#IdMikrolokacije");
                            mikrolokacijeDropdown.empty();
                            //console.log(data);
                            $.each(data, function (index, item) {
                                mikrolokacijeDropdown.append($('<option/>', {
                                    value: item.idMikrolokacije,
                                    text: item.nazivMikrolokacije
                                }));
                            });
                        }
                    });
                }
                else {
                    $("#IdMikrolokacije").empty();
                }
            });

        });
    </script>
    }
<style>
    .nav-pills li a:hover {
        background-color: blue;
    }
</style>
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="bg-dark col-auto col-md-2 min-vh-100 ">
            <div class="bg-dark p-2">
                <a class="d-flex text-decoration-none mt-5 align-items-center text-white">
                    <span class="fs-4 d-none d-sm-inline">SideMenu</span>
                </a>
                <ul class="nav nav-pills flex-column mt-4">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/Admin/PocetnaAdmin">
                            Pocetna
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/Admin/ProdateNekretnine">
                            Prodate nekretnine
                        </a>
                    </li>
                    <li class="nav-item py-2 py-sm-0">
                        <a class="nav-link text-white" href="/Admin/Agencije">
                            Agencije
                        </a>
                    </li>
                    <li class="nav-item py-2 py-sm-0">
                        <a class="nav-link text-white" href="/Admin/Mikrolokacije">
                            Mikrolokacije
                        </a>
                    </li>
                    <li class="nav-item py-2 py-sm-0">
                        <a class="nav-link text-white" href="/Admin/Ulice">
                            Ulice
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="container">
            <div class="col-md-9 main-content">
                <form method="post" asp-action="DodajUlicu" asp-controller="Admin" enctype="multipart/form-data">
                    <div class="form-group mb-2">
                       @* <label class="control-label">Naziv Mikrolokacije</label>*@
                        <div>
                            <input class="form-control" type="text" asp-for="NazivUlice" name="NazivUlice" placeholder="Naziv Ulice" />
                            <span asp-validation-for="NazivUlice" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group mb-2">
                        <label class="control-label">Grad</label>
                        <div>
                            <select class="form-select" id="CityId" name="CityId">
                                <option value="None" selected>Izaberi Grad</option>
                                @{
                                    foreach (var grad in ViewBag.Gradovi)
                                    {
                                        <option value="@grad.IdGrada">@grad.NazivGrada</option>
                                    }
                                }
                            </select>
                            @*<span asp-validation-for="IdTipGrejanja" class="text-danger"></span>*@
                        </div>
                    </div>
                    <div class="form-group mb-2">
                        @*<label class="control-label">Opstina</label>*@
                        <div>
                            <select class="form-select" id="IdOpstine" name="IdOpstine">
                                <option value="None" selected>Izaberi Opstinu</option>
                                <option></option>
                            </select>
                            @*<span asp-validation-for="IdTipGrejanja" class="text-danger"></span>*@
                        </div>
                    </div>
                    <div class="form-group mb-2">
                        @*<label class="control-label">Mikrolokacija</label>*@
                        <div>
                            <select class="form-select" id="IdMikrolokacije" name="IdMikrolokacije">
                                <option value="None" selected>Izaberi Mikrolokaciju</option>
                                <option></option>
                            </select>
                            @*<span asp-validation-for="IdTipGrejanja" class="text-danger"></span>*@
                        </div>
                    </div>
                    <div class="form-group text-center ">
                        <br />
                        <input type="submit" class="btn btn-primary btn-lg form-control" name="DodajUlicu" value="Nova Ulica" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>